package com.tm.dto;

public class TaskLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_label.label_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_label.task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String taskLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_label.used_flag
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String usedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_label.user_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_label.label_id
     *
     * @return the value of task_label.label_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_label.label_id
     *
     * @param labelId the value for task_label.label_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_label.task_label
     *
     * @return the value of task_label.task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getTaskLabel() {
        return taskLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_label.task_label
     *
     * @param taskLabel the value for task_label.task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setTaskLabel(String taskLabel) {
        this.taskLabel = taskLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_label.used_flag
     *
     * @return the value of task_label.used_flag
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getUsedFlag() {
        return usedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_label.used_flag
     *
     * @param usedFlag the value for task_label.used_flag
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setUsedFlag(String usedFlag) {
        this.usedFlag = usedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_label.user_id
     *
     * @return the value of task_label.user_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_label.user_id
     *
     * @param userId the value for task_label.user_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}