package com.tm.dto;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_title
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String taskTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String taskLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.start_date
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.deadline
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.completed_flag
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String completedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.user_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_note
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    private String taskNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_title
     *
     * @return the value of task.task_title
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getTaskTitle() {
        return taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_title
     *
     * @param taskTitle the value for task.task_title
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_label
     *
     * @return the value of task.task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getTaskLabel() {
        return taskLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_label
     *
     * @param taskLabel the value for task.task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setTaskLabel(String taskLabel) {
        this.taskLabel = taskLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.start_date
     *
     * @return the value of task.start_date
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.start_date
     *
     * @param startDate the value for task.start_date
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.deadline
     *
     * @return the value of task.deadline
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.deadline
     *
     * @param deadline the value for task.deadline
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.completed_flag
     *
     * @return the value of task.completed_flag
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getCompletedFlag() {
        return completedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.completed_flag
     *
     * @param completedFlag the value for task.completed_flag
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setCompletedFlag(String completedFlag) {
        this.completedFlag = completedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.user_id
     *
     * @return the value of task.user_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.user_id
     *
     * @param userId the value for task.user_id
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_note
     *
     * @return the value of task.task_note
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getTaskNote() {
        return taskNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_note
     *
     * @param taskNote the value for task.task_note
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setTaskNote(String taskNote) {
        this.taskNote = taskNote;
    }
}