package com.tm.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public TaskHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskTitleIsNull() {
            addCriterion("task_title is null");
            return (Criteria) this;
        }

        public Criteria andTaskTitleIsNotNull() {
            addCriterion("task_title is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTitleEqualTo(String value) {
            addCriterion("task_title =", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleNotEqualTo(String value) {
            addCriterion("task_title <>", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleGreaterThan(String value) {
            addCriterion("task_title >", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleGreaterThanOrEqualTo(String value) {
            addCriterion("task_title >=", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleLessThan(String value) {
            addCriterion("task_title <", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleLessThanOrEqualTo(String value) {
            addCriterion("task_title <=", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleLike(String value) {
            addCriterion("task_title like", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleNotLike(String value) {
            addCriterion("task_title not like", value, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleIn(List<String> values) {
            addCriterion("task_title in", values, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleNotIn(List<String> values) {
            addCriterion("task_title not in", values, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleBetween(String value1, String value2) {
            addCriterion("task_title between", value1, value2, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskTitleNotBetween(String value1, String value2) {
            addCriterion("task_title not between", value1, value2, "taskTitle");
            return (Criteria) this;
        }

        public Criteria andTaskLabelIsNull() {
            addCriterion("task_label is null");
            return (Criteria) this;
        }

        public Criteria andTaskLabelIsNotNull() {
            addCriterion("task_label is not null");
            return (Criteria) this;
        }

        public Criteria andTaskLabelEqualTo(String value) {
            addCriterion("task_label =", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelNotEqualTo(String value) {
            addCriterion("task_label <>", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelGreaterThan(String value) {
            addCriterion("task_label >", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelGreaterThanOrEqualTo(String value) {
            addCriterion("task_label >=", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelLessThan(String value) {
            addCriterion("task_label <", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelLessThanOrEqualTo(String value) {
            addCriterion("task_label <=", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelLike(String value) {
            addCriterion("task_label like", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelNotLike(String value) {
            addCriterion("task_label not like", value, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelIn(List<String> values) {
            addCriterion("task_label in", values, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelNotIn(List<String> values) {
            addCriterion("task_label not in", values, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelBetween(String value1, String value2) {
            addCriterion("task_label between", value1, value2, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andTaskLabelNotBetween(String value1, String value2) {
            addCriterion("task_label not between", value1, value2, "taskLabel");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNull() {
            addCriterion("deadline is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNotNull() {
            addCriterion("deadline is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineEqualTo(Date value) {
            addCriterion("deadline =", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotEqualTo(Date value) {
            addCriterion("deadline <>", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThan(Date value) {
            addCriterion("deadline >", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("deadline >=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThan(Date value) {
            addCriterion("deadline <", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("deadline <=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineIn(List<Date> values) {
            addCriterion("deadline in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotIn(List<Date> values) {
            addCriterion("deadline not in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineBetween(Date value1, Date value2) {
            addCriterion("deadline between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("deadline not between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagIsNull() {
            addCriterion("completed_flag is null");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagIsNotNull() {
            addCriterion("completed_flag is not null");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagEqualTo(String value) {
            addCriterion("completed_flag =", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagNotEqualTo(String value) {
            addCriterion("completed_flag <>", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagGreaterThan(String value) {
            addCriterion("completed_flag >", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("completed_flag >=", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagLessThan(String value) {
            addCriterion("completed_flag <", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagLessThanOrEqualTo(String value) {
            addCriterion("completed_flag <=", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagLike(String value) {
            addCriterion("completed_flag like", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagNotLike(String value) {
            addCriterion("completed_flag not like", value, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagIn(List<String> values) {
            addCriterion("completed_flag in", values, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagNotIn(List<String> values) {
            addCriterion("completed_flag not in", values, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagBetween(String value1, String value2) {
            addCriterion("completed_flag between", value1, value2, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andCompletedFlagNotBetween(String value1, String value2) {
            addCriterion("completed_flag not between", value1, value2, "completedFlag");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTaskNoteIsNull() {
            addCriterion("task_note is null");
            return (Criteria) this;
        }

        public Criteria andTaskNoteIsNotNull() {
            addCriterion("task_note is not null");
            return (Criteria) this;
        }

        public Criteria andTaskNoteEqualTo(String value) {
            addCriterion("task_note =", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteNotEqualTo(String value) {
            addCriterion("task_note <>", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteGreaterThan(String value) {
            addCriterion("task_note >", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteGreaterThanOrEqualTo(String value) {
            addCriterion("task_note >=", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteLessThan(String value) {
            addCriterion("task_note <", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteLessThanOrEqualTo(String value) {
            addCriterion("task_note <=", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteLike(String value) {
            addCriterion("task_note like", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteNotLike(String value) {
            addCriterion("task_note not like", value, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteIn(List<String> values) {
            addCriterion("task_note in", values, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteNotIn(List<String> values) {
            addCriterion("task_note not in", values, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteBetween(String value1, String value2) {
            addCriterion("task_note between", value1, value2, "taskNote");
            return (Criteria) this;
        }

        public Criteria andTaskNoteNotBetween(String value1, String value2) {
            addCriterion("task_note not between", value1, value2, "taskNote");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_history
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 24 09:20:46 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}