package com.tm.dao;

import com.tm.dto.TaskHistory;
import com.tm.dto.TaskHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    long countByExample(TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int deleteByExample(TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int insert(TaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int insertSelective(TaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    List<TaskHistory> selectByExample(TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    TaskHistory selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByExampleSelective(@Param("record") TaskHistory record, @Param("example") TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByExample(@Param("record") TaskHistory record, @Param("example") TaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByPrimaryKeySelective(TaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByPrimaryKey(TaskHistory record);
}