package com.tm.dao;

import com.tm.dto.TaskLabelHistory;
import com.tm.dto.TaskLabelHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskLabelHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    long countByExample(TaskLabelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int deleteByExample(TaskLabelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int deleteByPrimaryKey(String labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int insert(TaskLabelHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int insertSelective(TaskLabelHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    List<TaskLabelHistory> selectByExample(TaskLabelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    TaskLabelHistory selectByPrimaryKey(String labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByExampleSelective(@Param("record") TaskLabelHistory record, @Param("example") TaskLabelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByExample(@Param("record") TaskLabelHistory record, @Param("example") TaskLabelHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByPrimaryKeySelective(TaskLabelHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label_history
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByPrimaryKey(TaskLabelHistory record);
}