package com.tm.dao;

import com.tm.dto.TaskLabel;
import com.tm.dto.TaskLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    long countByExample(TaskLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int deleteByExample(TaskLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int deleteByPrimaryKey(String labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int insert(TaskLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int insertSelective(TaskLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    List<TaskLabel> selectByExample(TaskLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    TaskLabel selectByPrimaryKey(String labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByExampleSelective(@Param("record") TaskLabel record, @Param("example") TaskLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByExample(@Param("record") TaskLabel record, @Param("example") TaskLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByPrimaryKeySelective(TaskLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_label
     *
     * @mbg.generated Mon Dec 24 09:20:46 JST 2018
     */
    int updateByPrimaryKey(TaskLabel record);
}